sonar.projectKey=altaskur_OpenTimeTracker
sonar.projectName=OpenTimeTracker
sonar.organization=altaskur
sonar.sources=src/app,electron/src
sonar.exclusions=**/*.spec.ts,**/*.d.ts,**/*.html,**/*.scss,**/app.config.ts,**/app.routes.ts,**/themes/**,**/components/**,electron/src/main/**,electron/src/preload/**,electron/src/services/menu/**,electron/src/services/ipc/index.ts
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info,coverage/electron/lcov.info
sonar.qualitygate.wait=true
