name: Develop CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/jobs/tests.yml
