name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: Analyze
    uses: ./.github/workflows/test-and-analyze.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
